---
- name: Add pxelinux configuration file for machine being provisioned
  ansible.builtin.template:
    src: pxelinux.cfg
    dest: "{{ netboot_tftp_dir }}/pxelinux.cfg/01-{{ netboot_mac_addr | regex_replace(':', '-') | lower }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  delegate_to: "{{ netboot_server }}"

- name: Add grub configuration file for machine being provisioned
  ansible.builtin.template:
    src: grub.cfg
    dest: "{{ netboot_tftp_dir }}/grub/{{ netboot_mac_addr | lower }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  delegate_to: "{{ netboot_server }}"

- name: Configure preseed
  ansible.builtin.template:
    src: preseed/preseed.cfg
    dest: "{{ netboot_preseed_dir }}/{{ inventory_hostname }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  delegate_to: "{{ netboot_server }}"

- name: Confirm machine has been network booted
  ansible.builtin.pause:
    prompt: |-
      Please boot {{ inventory_hostname }} from the network to start the machine installation.

      After you have started the installation on the machine, press enter

- name: Wait before removing pxelinux, grub and preseed configuration files
  ansible.builtin.pause:
    seconds: "{{ netboot_wait.boot.post_delay }}"

- name: Remove pxelinux configuration file for machine being provisioned
  ansible.builtin.file:
    path: "{{ netboot_tftp_dir }}/pxelinux.cfg/01-{{ netboot_mac_addr | regex_replace(':', '-') | lower }}"
    state: absent
  delegate_to: "{{ netboot_server }}"

- name: Remove grub configuration file for machine being provisioned
  ansible.builtin.file:
    path: "{{ netboot_tftp_dir }}/grub/{{ netboot_mac_addr | lower }}"
    state: absent
  delegate_to: "{{ netboot_server }}"

- name: Remove preseed configuration file for machine being provisioned
  ansible.builtin.file:
    path: "{{ netboot_preseed_dir }}/{{ inventory_hostname }}"
    state: absent
  delegate_to: "{{ netboot_server }}"
